- name: Setup local machine
  hosts: 127.0.0.1
  connection: local
  roles:
    - Tahvok.vim
    - tmux
    - snap
    - {role: cmprescott.chrome, become: true}
    - {role: jdk, become: true}
    - ml
  tasks:
    - name: Instal packages
      become: true
      apt:
        update_cache: true
        pkg: "{{item}}"
        state: latest
      with_items:
        - curl
        - net-tools
    - name: Install aws cli
      become: true
      pip:
        name: awscli
        extra_args: --upgrade --user
