---
- name: Install tmux
  become: true
  apt:
    pkg: tmux
    state: latest
    update_cache: true
- name: Set tmux.conf
  file:
    src: "{{role_path}}/files/tmux.conf"
    dest: ~/.tmux.conf
    state: link
