---
- name: Create IDE directory
  file: path=~/IDE state=directory
- name: IntelliJ
  unarchive:
    src: https://download.jetbrains.com/idea/ideaIU-2017.3.4-no-jdk.tar.gz
    dest: ~/IDE
    remote_src: yes
